[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon_amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_KEY}"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
local = "${LOCAL_RPC_ENDPOINT}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", chain="84532", url="https://api-sepolia.basescan.org/api" }
